### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [viktorholk/pi-ledgame#1]
There is no license for this project. The default is copyright.

You should license this project under the AGPL3 or GPL3 license. If you would like me to submit a PR to make this easier, I would be happy to do that.

Cool project!  It reminds me of the arcade game stacker.  You should also populate a readme file with the information from reddit.  https://old.reddit.com/comments/bvqpgn

**Comment by viktorholk** [comment]
I someone only found this comment today.
But might as well give it a license and a proper readme, thanks
